FROM node:8.11.2-alpine as node
WORKDIR /usr/src/app
COPY package*.json ./ 
COPY requirements.txt ./ 
RUN npm install pip
RUN su pip install requirements 
COPY . . 
RUN python app.py 
# RUN npm run build 

# Stage 2
# FROM nginx:1.13.12-alpine
# COPY --from=node /usr/src/app/dist/ /usr/share/nginx/html
# COPY ./nginx.conf /etc/nginx/conf.d/default.conf 
