FROM gliderlabs/alpine:3.3

RUN apk add --update 
RUN apk add python3 

# RUN apk add python-dev 
# RUN purge python 
# RUN apk add py-pip 
# RUN pip install --upgrade python3-pip 
RUN apk add build-base 
RUN pip install virtualenv 
RUN rm -rf /var/cache/apk/*

WORKDIR /app

COPY . /app 
RUN virtualenv /env 
RUN /env/bin/pip install -r /app/requirements.txt

EXPOSE 8080 

CMD ["python3", "/app/app.py"]